### ISSUE TITLE
ModuleNotFoundError: No module named 'torch._custom_ops'

### ISSUE THREAD

**Issue by dangzhenmo** [Colmar-zlicheng/Spring-Gaus#3]
The ERROR occur when I try to train the data.I was using CUDA=11.8 and pytorch3D==0.7.4,I don't sure whether this is a potential reason or not.
The full ERROR report are as follow:
(base) PS F:\hhy\Spring-Gaus-main> python train.py -g 0 --cfg config/real_capture/burger.yaml --eval_cam 0 --exp_id burger
Traceback (most recent call last):
  File "F:\hhy\Spring-Gaus-main\train.py", line 30, in <module>
    from lib.utils.transform import inverse_sigmoid, uniform_sampling
  File "F:\hhy\Spring-Gaus-main\lib\utils\transform.py", line 11, in <module>
    import torchvision.transforms.functional as tvF
  File "C:\Users\Administrator\anaconda3\Lib\site-packages\torchvision\__init__.py", line 6, in <module>
    from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils
  File "C:\Users\Administrator\anaconda3\Lib\site-packages\torchvision\_meta_registrations.py", line 4, in <module>
    import torch._custom_ops
ModuleNotFoundError: No module named 'torch._custom_ops'

**Comment by dangzhenmo** [comment]
also I'm using python=3.11 in the base env

**Comment by Colmar-zlicheng** [comment]
Hi, it looks like a package version problem, maybe try reinstall pytorch and torchvision can help.

**Comment by sLeency** [comment]
I have the same problem.Have you solved it?

**Comment by sLeency** [comment]
I tried reinstalling torch and torchvision,but it didn't work.

**Comment by Colmar-zlicheng** [comment]
> I tried reinstalling torch and torchvision,but it didn't work.

Can you provide your torch version?

**Comment by dangzhenmo** [comment]
> I didn't solve the problem.

**Comment by Colmar-zlicheng** [comment]
> > I didn't solve the problem.

What's your pytorch version and torchvision version?

**Comment by dangzhenmo** [comment]
> Hi, it looks like a package version problem, maybe try reinstall pytorch and torchvision can help.
> 
> You can use the recommend environment at https://github.com/Colmar-zlicheng/Spring-Gaus?tab=readme-ov-file#rocket-dependencies 
Thank you vert much.I guess maybe the main reason of error is I didn't install pytorch3D==0.7.1 which is supported for python==3.7 and CUDA==11.6 at the same time.
But I only found the linux download source from here:https://anaconda.org/pytorch3d/pytorch3d/files?page=7 
Since I am using windows and my homework was ended  I give up on this project.

**Comment by dangzhenmo** [comment]
It seems that windows only supported pytorch3D==0.7.4 and it is no longer support python==3.7
